# Generated by Django 4.2.6 on 2023-11-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_details_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='campus',
            field=models.CharField(default='NVC'),
        ),
    ]
