# Generated by Django 4.2.6 on 2023-11-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_details_is_sold_details_is_wishlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='is_sold',
        ),
    ]
