# Generated by Django 4.2.6 on 2023-11-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_details_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='is_wishlist',
        ),
    ]
