# Generated by Django 4.2.6 on 2023-10-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentswap', '0002_alter_item_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
