# Generated by Django 4.2.6 on 2023-11-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentswap', '0004_item_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recently_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
