# Generated by Django 4.2.6 on 2023-11-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentswap', '0005_item_recently_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comments',
            field=models.JSONField(default=list),
        ),
    ]
