# Generated by Django 4.2.6 on 2023-11-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentswap', '0006_item_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_posted',
        ),
    ]
