# Generated by Django 4.2.6 on 2023-11-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentswap', '0008_item_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
