# Generated by Django 4.2.6 on 2023-11-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentswap', '0010_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_wishlist',
        ),
        migrations.RemoveField(
            model_name='item',
            name='recently_viewed',
        ),
    ]
