# Generated by Django 4.2.6 on 2023-11-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentswap', '0011_remove_item_is_sold_remove_item_is_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
