# Generated by Django 4.2.6 on 2023-11-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentswap', '0012_item_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
    ]
