# Generated by Django 4.2.6 on 2023-11-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentswap', '0013_remove_item_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='comments',
        ),
    ]
