# Generated by Django 4.2.6 on 2023-11-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
